// asciidoctor
:doctype: book
:toc2: left
:toc-title: Содержание
:note-caption: Примечание
:warning-caption: Важно!
:last-update-label: Редакция от
:version-label: Версия
:toclevels: 4
:sectnumlevels: 4


= Перечень элементов
:author: Барановский Константин
:email: baranovskiykonstantin@gmail.com
:revnumber: 1.0

Справочное руководство


== Введение

Перечень элементов выполнен в виде текстового документа и оформлен согласно
требованиям ЕСКД. +
Документ содержат макросы, позволяющие автоматически построить перечень,
заполнить основную надпись и добавить лист регистрации изменений.
Информация об элементах схемы и содержимое основной надписи извлекается из
списка цепей проекта KiCad. +
В документ встроены необходимые шрифты.


== Оформление документа


=== Стили страниц

Внешний вид первого листа можно изменить путём выбора стиля страницы. +
В документе для этого имеется четыре специальных стиля:

* *Первый лист 1* -- первый лист без дополнительных граф
* *Первый лист 2* -- первый лист с дополнительными графами _Справ. №_ и
_Перв. примен._
* *Первый лист 3* -- первый лист с дополнительными графами заказчика
* *Первый лист 4* -- первый лист со всеми дополнительными графами

Чтобы применить нужный стиль, нужно выполнить команду меню
`Стили -> Управление стилями (F11)`, выбрать `Стили страниц` и двойным
щелчком левой кнопки мыши установить один из выше перечисленных стилей. При
смене стиля форматной рамки с заполненной основной надписью данные сохраняются.

Для второго и последующих листов всегда используется стиль *Последующие листы*.

Во всех перечисленных стилях страниц, в качестве форматной рамки выступает
фоновое изображение.


=== Основная надпись и графы форматной рамки

Графы основной надписи и форматной рамки выполнены с помощью врезок. Заголовки
граф защищены от перемещения, изменения размера и редактирования.

Графы, предназначенные для ввода текста, защищены только от перемещения и
изменения размера. Не все графы форматной рамки имеют врезки для ввода текста.
Например, графы _Подп. и дата_, у левого края форматной рамки, врезок для ввода
текста не имеют.

Все врезки основной надписи и форматной рамки принадлежат нижнему колонтитулу и
хранятся в стиле страницы. Каждый стиль первого листа имеет свой собственный
набор врезок. При внесении изменений в графу основной надписи или форматной
рамки, соответствующие врезки остальных стилей синхронизируются посредством
макросов. Это позволяет изменять вид первого листа не теряя данных.

Структура стиля второго и последующих листов аналогична. Но здесь все графы
защищены от записи. Их значения синхронизируются с соответствующими врезками
первого листа с помощью макросов.

Номера и количество страниц подставляется автоматически средствами LibreOffice
(используются _поля_). Если в документе лишь одна страница, то графа _Листов_,
основной надписи первого листа, остаётся пустой. Это реализовано на основе
_скрытого абзаца_ с условием.

При заполнении основной надписи с помощью команды `Заполнить осн. надпись` в
графах фамилий для _Разраб._, _Пров._ и _Утв._ ширина шрифта автоматически
подбирается так, чтобы содержимое полностью поместилось в поле графы. При вводе
фамилий и инициалов вручную, ширину шрифта, если потребуется, нужно подобрать
самостоятельно.


=== Таблица перечня элементов

Перечень элементов представляет собой таблицу, которая занимает всю ширину
документа. Количество строк таблицы зависит от количества элементов схемы. Если
таблица не помещается на странице, то создаётся новый лист и она продолжается
на новой странице. Заголовок таблицы повторяется на каждом листе. Это
обеспечивается средствами LibreOffice.

С помощью макросов высота строк регулируется таким образом, чтобы нижнее
обрамление совпадало с верхней линией основной надписи.

В каждой графе таблицы используется отдельный стиль абзаца, соответствующий
наименованию графы. Кроме того, для графы _Наименование_ создано два стиля
абзацев: _Наименование_ и _Наименование (заголовок)_. Это сделано для того
чтобы можно было задать форматирование заголовка группы элементов отличное от
остального содержимого.

Стили абзацев таблицы являются _автообновляемыми_. То есть, при изменении
форматирования одной ячейки, автоматически изменяется форматирование остальных
ячеек этой графы. Например, по умолчанию в графе _Поз. обозначение_ текст
выровнен по левому краю. Если установить курсор в одну из ячеек этой графы
(любую) и задать выравнивание по центру, то все позиционные обозначения станут
выровненными по центру.

Не все команды форматирования применяются ко целому абзацу. К примеру,
подчёркивание применяется к символам. Чтобы подобные изменения были
автоматически отражены на остальных ячейках с таким же стелем, нужно сначала
выделить всё содержимое ячейки и потом применить форматирование. +
По умолчанию, наименование группы элементов (заголовок) имеет обычное
начертание. Чтобы сделать его подчёркнутым нужно установить курсор в ячейку с
любым заголовком, выделить всё содержимое ячейки с помощью мыши или нажатием
комбинации клавиш `Ctrl+A` и выполнить команду меню `Формат -> Текст ->
Подчёркнутый (Ctrl+U)`. Заголовки всех групп элементов станут подчёркнутыми.

Таблицы открытого формата документов для офисных приложений (ODF) имеют одну
особенность о которой стоит упомянуть: после таблицы обязательно должен быть
как минимум один абзац. То есть, документ не может заканчиваться таблицей. +
В случае с перечнем элементов возникает следующая ситуация. Если таблица
перечня занимает всю страницу так, что обрамление последней строки совпадает с
верхней линией основной надписи, то абзац после таблицы (который нельзя
удалить) переносится на новую чистую страницы. Чтобы избежать подобного,
последнему абзацу присвоен особый стиль _Пустой_, который имеет минимально
возможную высоту (приблизительно 0.5 мм), а отступ между нижним колонтитулом и
содержимым документа уменьшен на величину данного абзаца. В таком варианте
абзац после таблицы не переносится на следующую страницу, а просто
накладывается на нижний колонтитул с основной надписью. Это не влияет на
внешний вид, но при редактировании документа вручную об этом следует помнить.


=== Начертание текста

Графы таблицы перечня элементов и графы форматной рамки имеют собственные стили
абзацев. Но все они происходят от одного общего стиля -- _Текст_ и наследуют
его свойства.

Чтобы изменить начертание текста необходимо открыть окно управления стилями,
выполнив команду меню `Стили -> Управление стилями (F11)`, и нажать кнопку
`Стили абзацев`. В списке стилей нажать правой кнопкой мыши на пункте _Текст_ и
в контекстном меню выбрать команду `Изменить...`. В открывшемся диалоговом
окне, на вкладке _Шрифт_, можно установить необходимое начертание текста в поле
_Стиль_. _Обычный_ стиль соответствует прямому начертанию, а _Курсив_ --
наклонному. После применения изменений все надписи в документе будут
отображаться с указанным начертанием.
