// asciidoctor
:doctype: book
:toc2: left
:toc-title: Содержание
:last-update-label: Редакция от
:version-label: Версия
:toclevels: 4
:sectnumlevels: 4
:note-caption: !


= Ведомость покупных изделий
:author: Барановский Константин
:email: baranovskiykonstantin@gmail.com
:revnumber: : \
include::../../../../version[]

Справочное руководство


== Введение

Ведомость покупных изделий выполнена в виде текстового документа и оформлена
согласно требованиям ЕСКД. +
Документ построен таким образом, чтобы максимально упростить процесс заполнения
ведомости и основной надписи:

* документ содержит макросы, позволяющие автоматически построить ведомость
покупных изделий и заполнить основную надпись (информация об элементах схемы и
содержимое основной надписи извлекается из списка цепей проекта KiCad);
* имеется возможность добавить/удалить лист регистрации изменений;
* автоматически подстраивается высота строк таблицы ведомости;
* автоматически подстраивается масштаб текста по ширине графы ведомости или
основной надписи;
* стили элементов документа имеют древовидную структуру, что позволяет
изменять форматирование сразу группы однотипных элементов.
* графы таблицы имеют собственные автообновляемые стили, что позволяет
применять форматирование ко всей графе сразу;
* в документ встроены необходимые шрифты.

Чтобы получить ведомость покупных изделий для проекта KiCad нужно пройти
следующие шаги:

1) заполнить поля компонентов схемы должным образом и обновить список цепей; +
2) на основе шаблона документа создать новую ведомость покупных изделий и
сохранить её в каталоге проекта KiCad; +
3) настроить параметры формирования ведомости; +
4) запустить макрос построения ведомости; +
5) запустить макрос заполнения основной надписи; +
6) при необходимости, поправить форматирование и содержимое ведомости покупных
изделий.


== Поля компонентов схемы

При формировании ведомости покупных изделий для неподготовленного проекта KiCad
будут использовано только одно стандартное поле компонентов:

Значение ::
помещается в графу _Наименование_

[NOTE]
====

Если поле компонента, соответствующее параметру _Поля->Наименование_, пусто или
отсутствует, то вместо него используется поле _Значение_.

====

Для получения полноценной ведомости покупных изделий, компонентам схемы следует
добавить несколько пользовательских полей. Количество дополнительных полей и их
содержимое зависит от типа компонента и от данных, которые должны быть
отображены в ведомости. По умолчанию макросами используются следующие поля
компонентов:

Тип ::
пользовательское поле, в котором хранится описание типа компонента,
например, _Резистор {Резисторы}_. Значение этого поля указывается в графе
_Наименование_ и выступает в виде заголовка однотипных компонентов. +
В зависимости от параметров построения ведомости, тип компонента может
указываться как в единственном, так и в множественном числе, поэтому формат
поля _Тип_ имеет сложный вид: +
`Тип в единственном числе {Тип в множественном числе}` +
Сначала указывается форма в единственном числе, за которой через пробел и в
фигурных скобках следует форма в множественном числе. Если содержимое не
соответствует описанному формату, то оно будет использовано полностью, как в
единственной, так и в множественной формах. Но при активном режиме
совместимости с _kicadbom2spec_, будет предпринята попытка найти формы
единственного и множественного числа в словаре групп из конфигурационного файла
приложения _kicadbom2spec_.
Наименование ::
пользовательское поле, в котором содержится полное наименование
компонента. Содержимое этого поля помещается в графу _Наименование_. Если поле
пусто или отсутствует, то вместо него используется стандартное поле _Значение_.
Код продукции ::
пользовательское поле. Содержимое указанного поля помещается в графу _Код
продукции_.
Документ ::
пользовательское поле, в котором указывается ГОСТ, ТУ или другой документ,
относящийся к компоненту. Содержимое этого поля помещается в графу
_Обозначение документа на поставку_.
Поставщик ::
пользовательское поле. Содержимое указанного поля помещается в графу
_Поставщик_.
Куда входит ::
пользовательское поле. Содержимое указанного поля помещается в графу
_Куда входит (обозначение)_.
Примечание ::
пользовательское поле, содержимое которого помещается в одноимённую графу
ведомости после перечня обозначений компонентов.
Исключить ::
пользовательское поле. Если поле с указанным именем содержится в компоненте, то
такой компонент будет исключён из ведомости. Значение самого поля не
используется.

Предложенные наименования полей можно изменить на вкладке _Поля_ диалогового
окна параметров макросов.

Значение поля компонента может включать содержимое других полей этого же
компонента. Это реализуется с помощью _Шаблонов_ -- текстовых конструкций,
которые обрабатываются особым образом.


=== Шаблоны

Шаблоном называется строка текста, содержащая как минимум одну конструкцию
следующего вида:

 ${поле}

или

 ${префикс|поле|суффикс}

префикс ::
символы между `{` и `|` будут добавлены к значению поля в виде префикса
поле ::
наименование поля, значение которого должно быть подставлено вместо конструкции
`${}`
суффикс ::
символы между `|` и `}` будут добавлены к значению поля в виде суффикса

Внутри конструкции `${}` символы `{`, `|` и `}` нужно экранировать с помощью
обратной косой черты: `\{`, `\|` или `\}`. За пределами конструкции `${}`
экранирование не требуется. Например, в шаблоне +
`| ${\{|Посад.место|\}} |` +
вертикальная черта в начале и конце строки экранирования не требует, так как
находится за пределами конструкции `${}`, а вот фигурные скобки в качестве
префикса и суффикса нужно экранировать.

[NOTE]
====

Так как внутри шаблона используется экранирование, то для отображения обратной
косой черты её тоже нужно экранировать `\\`. Например, чтобы установить перевод
строки в качестве суффикса нужно указать две обратных косых черты перед
символом `n`: +
`${\\n|Посад.место|}` +
За пределами шаблона обратная косая черта обрабатывается как обычный символ.

====

Шаблон может содержать несколько конструкций вида `${}`.

Если указанное поле пусто или отсутствует, то конструкция `${}` просто
удаляется из текста.

Поле, указанное в конструкции `${}`, тоже может содержать шаблон. Но эти
шаблоны не должны ссылаться друг на друга, иначе возникнет рекурсивное
зацикливание.

Доступ к стандартным полям производится с помощью следующих имён:

* *Обозначение*
* *Значение*
* *Посад.место*
* *Документация*
* *Описание*

[NOTE]
====

Если указать _Посад.место_ с восклицательным знаком в конце `Посад.место!`, то
из значения этого поля будет удалено наименование библиотеки, оставив только
наименование посадочного места. +
Обратите внимание, имеется параметр
_"Посад.место" без наименования библиотеки_, который выполняет такую же
функцию, но применяется ко всем полям _Посад.место_.

====

[NOTE]
====

_Описание_ не является полем компонента. Это описание элемента из библиотеки
компонентов, но доступ к нему выполняется как к стандартному полю.

====

Шаблоны в стандартных полях тоже обрабатываются.

Рассмотрим пример шаблона для поля _Наименование_ резистора:

 МЛТ-0,5-${Значение}${-|Класс точности|}-В

Здесь имеются две конструкции `${}`, т.е. будут подставлены значения двух
полей _Значение_ и _Класс точности_. Значение не имеет ни префикса, ни
суффикса, а к классу точности будет добавлен префикс `-`. +
Предположим, сопротивление резистора равно `4,7кОм`, а класс точности `±5%`,
тогда шаблон будет преобразован в строку следующего вида:

 МЛТ-0,5-4,7кОм-±5%-В

Если класс точности не указан или такое поле отсутствует в компоненте, то
строка будет следующей:

 МЛТ-0,5-4,7кОм-В

т.е. класс точности и его префикс отсутствует в итоговом значении.


== Параметры

Параметры можно импортировать из другого документа. Для этого нужно нажать
кнопку `Импорт...` и выбрать документ.

Оптимальный вид документа ::
Если отмечено, то при открытии документа параметры отображения будут настроены
для обеспечения наилучшего вида содержимого:
* _Границы текста_ -- скрыть
* _Границы таблиц_ -- скрыть
* _Затенение полей_ -- отключить
* _Скрытые абзацы_ -- скрыть
* _Подробные всплывающие подсказки_ -- включить
* _Панель инструментов_ -- расположить под стандартными

=== Ведомость
Файл с данными о схеме ::
Источником данных о схеме является файл списка цепей KiCad. +
Если файл не указан, то при запуске макроса `Построить ведомость` или
`Заполнить осн. надпись` будет предпринята попытка найти файл списка цепей по
имени файла проекта (ищется файл _*.pro_, заменяется расширение _pro_ на _net_
и проверяется наличие файла с полученным именем и расширением). Если файл
списка цепей найти не удастся, будет показан диалог выбора файла. +
Поддерживаются файлы с расширением:
* _*.net_ -- формат Pcbnew `Eeschema -> Экспорт -> Экспорт списка цепей...`
* _*.xml_ -- вспомогательный `Eeschema -> Инструменты -> Сформировать
перечень элементов...`

[NOTE]
====

Вспомогательный файл списка цепей создаётся перед формированием перечня
элементов средствами _Eeschema_ и остаётся в каталоге проекта как побочный. В
__*.net__-файле и __*.xml__-файле содержатся одни и те же данные, только в
разных форматах.

====

Количество пустых строк между компонентами разного типа ::
Указанное количество пустых строк будет вставлено между компонентами различного
типа в разделе _Прочие изделия_.

Минимально допустимый масштаб по ширине (%) ::
Если текст не помещается в графе таблицы, то уменьшается масштаб символов по
ширине. Когда масштаб становится меньше указанного значения, текст разбивается
на части и размещается на последующих строках.

Добавить единицы измерения ::
Если для резисторов, конденсаторов или индуктивностей указаны только значения и
данная опция включена, то к значениям будут добавлены соответствующие единицы
измерения (Ом, Ф, Гн). При этом, множители приводятся к общему виду:

[width=40%,options="header"]
|===
|На схеме |В ведомости
2+^|**Конденсаторы**
|1.2 |1,2мкФ
|1200 |1200пФ
|1н2 |1,2нФ
|12 μF |12мкФ
|120u |120мкФ
2+^|**Резисторы**
|4.7 |4,7Ом
|4R7 |4,7Ом
|R47 |0,47Ом
|470 |470Ом
|4,7k |4,7кОм
|4.7 kOhm |4,7кОм
|4,7 kΩ |4,7кОм
|4M7 |4,7МОм
2+^|**Дроссели**
|910 |910мкГн
|910u |910мкГн
|910мк |910мкГн
|9m1 |9,1мГн
|910 uH |910мкГн
|===

Вставить пробел перед единицами измерения ::
Если отмечено, то между цифровой частью значения и единицами измерения (включая
множитель) будет вставлен пробел.

Формировать отдельную группу для каждого документа ::
По умолчанию, группы компонентов формируются по их типу, например: _Резисторы_,
_Конденсаторы_ и т.д. +
Если отмечено, то группы компонентов будут разбиваться ещё и по документу.

Формировать заголовок для каждой группы ::
По умолчанию, заголовок формируется только если группа содержит более чем один
компонент. +
Если же группа состоит из одного компонента, заголовок не формируется, а _Тип_,
в единственном числе, указывается перед _Наименованием_. Если отмечено, то
заголовок будет сформирован для каждой группы, даже если она состоит из одного
компонента.

Нумеровать только позиции компонентов ::
По умолчанию, номера позиций присваиваются каждой строке. Если отмечено, то
номера позиций будут указываться только для компонентов.

Резервировать номера позиций ::
По умолчанию, позиции в ведомости увеличиваются на единицу. +
Если отмечено, то для пустых строк, вставляемых между группами компонентов,
будут зарезервированы номера позиций.

Добавить пустую строку после заголовка группы ::
Если отмечено, то между заголовком и первым компонентом группы будет вставлена
одна пустая строка.

Добавить лист регистрации изменений, если количество листов больше ... ::
Если отмечено и при автоматическом построения таблицы количество листов
документа превысит указанное число, то в конец документа будет добавлен лист
регистрации изменений.

Запретить заголовки групп внизу страницы ::
Если отмечено, то заголовки групп, находящиеся внизу страницы без единого
элемента, будут перемещены на следующую страницу.

Запретить пустые строки вверху страницы ::
Если отмечено, то пустые строки вверху страницы будут удалены.

Обработать повторяющиеся значения в графах ::
Если отмечено, при первом повторении значения в графе, оно будет заменено
фразой `То же`, а далее кавычками `»`. +
Обрабатываются только следующие графы:
* _Код продукции_
* _Обозначение документа на поставку_
* _Поставщик_
* _Куда входит (обозначение)_
* _Примечание_

"Посад.место" без наименования библиотеки ::
Поле _Посад.место_ содержит значение в формате
`Наименование_библиотеки:Посад_место`. +
Если отмечено, то из значения поля _Посад.место_ будет удаляться наименование
библиотеки включительно с двоеточием, оставляя только наименование посадочного
места.

Обрабатывать "\n" как переход на новую строку ::
Если отмечено, то комбинация символов `\n` будет обрабатываться как переход
на следующую строку таблицы.


=== Поля

Тип ::
Значение поля с указанным именем будет использовано для обозначения типа
компонента, например, _Резистор {Резисторы}_.

Наименование ::
Значение поля с указанным именем будет помещено в графу _Наименование_.

Код продукции ::
Значение поля с указанным именем будет помещено в графу _Код продукции_.

Документ ::
Значение поля с указанным именем будет добавлено к _Наименованию_, указывая на
ГОСТ, ТУ или прочий документ.

Поставщик ::
Значение поля с указанным именем будет помещено в графу _Поставщик_.

Куда входит ::
Значение поля с указанным именем будет помещено в графу _Куда входит
(обозначение)_.

Примечание ::
Значение поля с указанным именем будет помещено в графу _Примечание_.

====

В обозначенных выше полях допускается использование _шаблонов_. Благодаря этому
можно комбинировать значения нескольких полей.

Если значение, указанное в поле параметра, не содержит конструкций `${}`, то
оно воспринимается как наименование поля и в ведомости будет использовано
значение данного поля.

Если же в значении параметра имеется хотя бы одна конструкция `${}`, то такое
значение будет обработано как _шаблон_ и в ведомость попадёт преобразованный
текст с подставленными значениями указанных полей.

*Примечание:* если значение для поля _Тип_ указано в виде шаблона, то к
единственному/множественному числу будет приведено каждое значение из указанных
полей. Если содержимое поля не соответствует формату `тип в единственном числе
{тип в множественном числе}`, то это содержимое будет использоваться полностью
как в единственном, так и в множественном числе.

Для примера можно рассмотреть _Наименование_ в режиме совместимости с
_kicadbom2spec_:

 ${|Марка|-}${Значение}${-|Класс точности|}${-|Тип|}

Здесь наименование состоит из нескольких частей, каждая из которых храниться в
отдельном поле компонента.

*Примечание:* при нажатии кнопки `Установить значения, совместимые с
kicadbom2spec` шаблон _Наименования_ будет построен с учётом разделителей,
указанных в конфигурационном файле приложения _kicadbom2spec_ (если он
существует).

Обратите внимание, значения:

 Наименование

и

 ${Наименование}

в итоге дадут одинаковый результат -- значение поля с именем _Наименование_. Но
обработаны они будут по разному, в первом случае -- значение воспринимается как
название поля, а во втором -- как шаблон.

====

Исключить ::
Если компонент содержит поле с указанным именем, то он будет исключён из
ведомости.

Установить значения по умолчанию ::
Установить параметрам полей значения по умолчанию.

Установить значения, совместимые с kicadbom2spec ::
Настроить параметры полей так, чтобы обеспечить формирование ведомости для
проектов, оформленных с помощью приложения _kicadbom2spec_.

Режим совместимости с kicadbom2spec ::
Если отмечено, то при формировании ведомости из файла настроек приложения
_kicadbom2spec_ будут использованы данные о разделителях и словарь наименований
групп.

=== Основная надпись

Преобразовать наименование документа ::
Если отмечено, тип схемы в наименовании документа будет заменён надписью
_Ведомость покупных изделий_. +
В противном случае, наименование останется без изменений.

Преобразовать обозначение документа ::
Если отмечено, вместо типа схемы в обозначении документа будет указан код
_ВП_. +
В противном случае, обозначение останется без изменений.

Автоматически заполнить графу _Перв. примен._ ::
Если отмечено, в графу первичной применяемости будет записано обозначение
документа без кода документа. +
В противном случае, графа останется без изменений.

Использовать имя файла в качестве типа документа ::
Если отмечено, и активен параметр _Преобразовать наименование документа_,
то в качестве типа документа будет указано имя файла. +
Например, если при создании ведомости ей было присвоено имя _Ведомость
покупных ЭРЭ.odt_, то при заполнении основной надписи вместо _Ведомость
покупных изделий_ будет указано _Ведомость покупных ЭРЭ_.


== Панель инструментов

Построить ведомость ::
запустить макрос построения ведомости покупных изделий. Содержимое таблицы
будет перезаписано.

Очистить ведомость ::
запустить макрос очистки ведомости. Таблица будет удалена и построена заново.

---

Заполнить осн. надпись ::
запустить макрос заполнения основной надписи. Данные для заполнения будут взяты
из файла списка цепей.

Очистить осн. надпись ::
запустить макрос очистки основной надписи. Содержимое граф основной надписи и
форматной рамки будет удалено, а форматирование установлено к значениям по
умолчанию. +
Графы _Лист_ и _Листов_ данным макросом не затрагиваются.

---

Добавить/удалить лист рег. изм. ::
запустить макрос создания/удаления листа регистрации изменений. +
Если лист регистрации изменений отсутствует в документе, то он будет создан в
виде последней страницы и отделён от таблицы ведомости разрывом страниц. +
В противном случае -- лист регистрации изменений будет удалён из документа.

---

Параметры ::
показать диалоговое окно для ввода параметров формирования ведомости.

---

Справка ::
открыть справочное руководство в вэб-браузере.


== Оформление документа

=== Стили страниц

Внешний вид первого листа можно изменить путём выбора стиля страницы. +
В документе для этого имеется четыре специальных стиля:

* *Первый лист 1* -- первый лист без дополнительных граф
* *Первый лист 2* -- первый лист с дополнительными графами _Справ. №_ и
_Перв. примен._
* *Первый лист 3* -- первый лист с дополнительными графами заказчика
* *Первый лист 4* -- первый лист со всеми дополнительными графами

Чтобы применить нужный стиль, нужно выполнить команду меню
`Стили -> Управление стилями (F11)`, выбрать `Стили страниц` и двойным
щелчком левой кнопки мыши установить один из выше перечисленных стилей. При
смене стиля форматной рамки с заполненной основной надписью -- данные
сохраняются.

Для второго и последующих листов всегда используется стиль *Последующие листы*.

Во всех перечисленных стилях страниц, в качестве форматной рамки выступает
фоновое изображение.


=== Основная надпись и графы форматной рамки

Графы основной надписи и форматной рамки построены из врезок. Заголовки граф
защищены от перемещения, изменения размера и редактирования. Графы,
предназначенные для ввода текста, защищены только от перемещения и изменения
размера. Не все графы форматной рамки имеют врезки для ввода текста. Например,
графа _Подп._ основной надписи врезок для ввода текста не имеет.

Все врезки основной надписи и форматной рамки принадлежат нижнему колонтитулу и
хранятся в стиле страницы. Каждый стиль первого листа имеет свой собственный
набор врезок. При внесении изменений в графу основной надписи или форматной
рамки, соответствующие врезки остальных стилей синхронизируются посредством
макросов. Это позволяет изменять вид первого листа без потери данных.

Структура стиля второго и последующих листов аналогична. Но здесь все графы
защищены от записи. Их значения синхронизируются с соответствующими врезками
первого листа с помощью макросов.

Номера и количество страниц подставляются автоматически средствами LibreOffice
(используются _поля_). Если в документе лишь одна страница, то графа _Лист_,
основной надписи первого листа, остаётся пустой. Это реализовано на основе
_скрытого абзаца_ с условием.

Автоматический подбор масштаба шрифта по ширине работает как при заполнении
основной надписи с помощью команды `Заполнить осн. надпись`, так и при вводе
текста вручную. Текст обрабатывается построчно.


=== Таблица ведомости покупных изделий

Ведомость представляет собой таблицу, которая занимает всю ширину документа.
Количество строк таблицы зависит от количества элементов схемы. Если таблица не
помещается на странице, то создаётся новый лист и она продолжается на новой
странице. Заголовок таблицы повторяется на каждом листе. Это обеспечивается
средствами LibreOffice.

С помощью макросов высота строк регулируется таким образом, чтобы нижняя линия
обрамления последней строки на странице совпадала с верхней линией основной
надписи.

В каждой графе таблицы используется отдельный стиль абзаца, соответствующий
наименованию графы. Кроме того, для графы _Наименование_ создано два стиля
абзацев: _Наименование_ и _Наименование (заголовок)_. Это сделано для того,
чтобы можно было задать форматирование заголовка группы элементов отличное от
остального содержимого.

Стили абзацев таблицы являются _автообновляемыми_. То есть, при изменении
форматирования одной ячейки, автоматически изменяется форматирование остальных
ячеек этой графы. Например, по умолчанию в графе _Примечание_ текст
выровнен по левому краю. Если установить курсор в одну из ячеек этой графы
(любую) и задать выравнивание по центру, то все позиционные обозначения станут
выровненными по центру.

Не все команды форматирования применяются к целому абзацу. К примеру,
подчёркивание применяется к символам. Чтобы подобные изменения были
автоматически отражены на остальных ячейках с таким же стелем, нужно применить
форматирование ко всему содержимому ячейки. +
По умолчанию, наименование группы элементов (заголовок) имеет обычное
начертание. Чтобы сделать его подчёркнутым, нужно установить курсор в ячейку с
любым заголовком, выделить всё содержимое ячейки с помощью мыши или нажатием
комбинации клавиш `Ctrl+A` и выполнить команду меню `Формат -> Текст ->
Подчёркнутый (Ctrl+U)`. Заголовки всех групп элементов станут подчёркнутыми.

[NOTE]
====

Открытый формат документов для офисных приложений (ODF) имеет несколько
особенностей о которых стоит упомянуть.

После таблицы обязательно должен быть как минимум один абзац. То есть, документ
не может заканчиваться таблицей. +
В случае с ведомостью покупных изделий возникает следующая ситуация. Если
таблица ведомость занимает всю страницу так, что обрамление последней строки
совпадает с верхней линией основной надписи, то абзац после таблицы (который
нельзя удалить) переносится на новую чистую страницу. Чтобы избежать подобного,
последнему абзацу присвоен особый стиль _Пустой_, который имеет минимально
возможную высоту (приблизительно 0.5 мм), а отступ между нижним колонтитулом и
содержимым документа уменьшен на величину данного абзаца. В таком варианте
абзац после таблицы не переносится на следующую страницу, а просто
накладывается на нижний колонтитул с основной надписью. Это не влияет на
внешний вид, но при редактировании документа вручную, об этом следует помнить.

Ещё одна особенность была выявлена при создании шаблона. Если таблица находится
в самом начале документа и в ячейках используются автообновляемые стили
абзацев, то при первом же редактировании таких ячеек, стиль страницы
сбрасывается на стиль по умолчанию. +
Чтобы избежать подобного поведения, перед таблицей добавляется специальный
_Пустой_ абзац, а поле первой страницы расширено вверх на величину данного
абзаца, чтобы таблица начиналась у верхнего края форматной рамки.

====


=== Начертание текста

Графы таблицы ведомости и графы форматной рамки имеют собственные стили
абзацев. Но все они происходят от одного общего стиля -- _Текст_ и наследуют
его свойства.

Чтобы изменить начертание текста во всём документе необходимо открыть окно
управления стилями, выполнив команду меню `Стили -> Управление стилями (F11)`,
и нажать кнопку `Стили абзацев`. В списке стилей нажать правой кнопкой мыши на
пункте _Текст_ и в контекстном меню выбрать команду `Изменить...`. В
открывшемся диалоговом окне, на вкладке _Шрифт_, можно установить необходимое
начертание текста в поле _Стиль_. _Обычный_ стиль соответствует прямому
начертанию, а _Курсив_ -- наклонному. После применения изменений все надписи в
документе будут отображаться с указанным начертанием.


=== Размер шрифта таблицы

По умолчанию, размер шрифта заголовка составляет 18 пунктов, а содержимого
таблицы ведомости -- 16 пунктов. +

При желании, размер шрифта содержимого таблицы можно изменить, например,
уменьшить до 14 пунктов. Для этого нужно открыть окно управления стилями,
выполнив команду меню `Стили -> Управление стилями (F11)`, и нажать кнопку
`Стили абзацев`. В списке стилей нажать правой кнопкой мыши на пункте _Значение
графы таблицы_ и в контекстном меню выбрать команду `Изменить...`. В
открывшемся диалоговом окне, на вкладке _Шрифт_, можно установить желаемый
размер шрифта в поле _Кегль_.

Автоматическая подстройка ширины текста будет нормально работать с новым
размером шрифта при вводе новых данных. Но если ведомость была построена
до изменения размера шрифта, потребуется сформировать ведомость заново,
чтобы макрос автоматически подобрал масштаб шрифта по ширине, а при
необходимости разбил содержимое на несколько строк.


=== Номера строк

Номера строк в ведомости выполнены с помощью _полей_. Значение поля
формируется с применением переменной _Позиция_. По умолчанию поле позиции имеет
значение `Позиция+1`, то есть номер позиции увеличивается на единицу по
отношению к предыдущей. Если установлен параметр _Резервировать номера
позиций_, то позиция после нескольких пустых строк будет увеличена не на
единицу, на количество пустых строк плюс 1.

Чтобы исправить номер строки нужно дважды щёлкнуть левой кнопки мыши по нему и
в открывшемся диалоговом окне поправить инкремент в поле _Значение_.
