// asciidoctor
:doctype: book
:toc2: left
:toc-title: Содержание
:last-update-label: Редакция от
:version-label: Версия
:toclevels: 4
:sectnumlevels: 4
:note-caption: !


= Пояснительная записка
:author: Барановский Константин
:email: baranovskiykonstantin@gmail.com
:revnumber: 1.2

Справочное руководство


== Введение

Пояснительная записка оформлена согласно требованиям ЕСКД. +
Документ содержит макросы, позволяющие автоматически заполнить основную надпись
и добавить/удалить лист регистрации изменений (содержимое основной надписи
извлекается из списка цепей проекта KiCad). +
В документ встроены необходимые шрифты.


== Параметры

Оптимальный вид документа ::
Если отмечено, то при открытии документа параметры отображения будут настроены
для обеспечения наилучшего вида содержимого:
* _Границы текста_ -- скрыть
* _Границы таблиц_ -- скрыть
* _Затенение полей_ -- отключить
* _Скрытые абзацы_ -- скрыть
* _Подробные всплывающие подсказки_ -- включить
* _Панель инструментов_ -- расположить под стандартными

=== Пояснительная записка
Файл с данными о схеме ::
Источником данных о схеме является файл списка цепей KiCad. +
Если файл не указан, то при запуске макроса `Построить перечень` или
`Заполнить осн. надпись` будет предпринята попытка найти файл списка цепей по
имени файла проекта (ищется файл _*.pro_, заменяется расширение _pro_ на _net_
и проверяется наличие файла с полученным именем и расширением). Если файл
списка цепей найти не удастся, будет показан диалог выбора файла. +
Поддерживаются файлы с расширением:
* _*.net_ -- формат Pcbnew `Eeschema -> Экспорт -> Экспорт списка цепей...`
* _*.xml_ -- вспомогательный `Eeschema -> Инструменты -> Сформировать
перечень элементов...`

[NOTE]
====

Вспомогательный файл списка цепей создаётся перед формированием перечня
элементов средствами _Eeschema_ и остаётся в каталоге проекта как побочный. В
__*.net__-файле и __*.xml__-файле содержатся одни и те же данные, только в
разных форматах.

====

=== Основная надпись

Преобразовать наименование документа ::
Если отмечено, тип схемы в наименовании документа будет заменён надписью
_Пояснительная записка_. +
В противном случае, наименование останется без изменений.

Преобразовать обозначение документа ::
Если отмечено, вместо типа схемы в обозначении документа будет указан
код _ПЗ_. +
В противном случае, обозначение останется без изменений.

Автоматически заполнить графу _Перв. примен._ ::
Если отмечено, в графу первичной применяемости будет записано обозначение
документа без кода документа. +
В противном случае, графа останется без изменений.


== Панель инструментов

Заполнить осн. надпись ::
запустить макрос заполнения основной надписи. Данные для заполнения будут взяты
из файла списка цепей.

Очистить осн. надпись ::
запустить макрос очистки основной надписи. Содержимое граф основной надписи и
форматной рамки будет удалено, а форматирование установлено к значениям по
умолчанию. +
Графы _Лист_ и _Листов_ данным макросом не затрагиваются.

---

Добавить/удалить лист рег. изм. ::
запустить макрос создания/удаления листа регистрации изменений. +
Если лист регистрации изменений отсутствует в документе, то он будет создан в
виде последней страницы и отделён от содержимого документа разрывом страниц. +
В противном случае -- лист регистрации изменений будет удалён из документа.

---

Параметры ::
показать диалоговое окно для ввода параметров работы макросов.

---

Справка ::
открыть справочное руководство в вэб-браузере.


== Оформление документа

=== Стили страниц

Шаблон содержит два варианта стилей титульного листа:

* *Титульный лист 1* -- титульный лист без граф, только рамка
* *Титульный лист 2* -- титульный лист с графами у левого края листа

Чтобы сформировать титульный лист необходимо установит курсор на первом листе
документа и выполнить команду меню `Стили -> Управление стилями (F11)`, нажать
кнопку `Стили страниц` и двойным щелчком мыши применить один из выше указанных
стилей к странице.

По умолчанию используется стиль _Титульный лист 1_.

После титульного листа идёт заглавный лист. В шаблоне имеется четыре варианта
стилей заглавного листа:

* *Первый лист 1* -- первый лист без дополнительных граф
* *Первый лист 2* -- первый лист с дополнительными графами _Справ. №_ и
_Перв. примен._
* *Первый лист 3* -- первый лист с дополнительными графами заказчика
* *Первый лист 4* -- первый лист со всеми дополнительными графами

По умолчанию, за титульным листом следует _Первый лист 1_.

Чтобы изменить формат заглавного листа нужно править стиль титульного листа.
Для этого нужно выполнить команду `Стили -> Управление стилями (F11)` и перейти
к `стилям страниц`. Далее найти формат, использованный для титульного листа
документа, и через контекстное меню выполнить команду `Изменить...`. В
открывшемся диалоговом окне, на вкладке `Управление`, в поле `Следующий стиль`,
указать вариант заглавного листа.

Если в документе титульный лист не требуется, то первому листу присваивается
один из стилей заглавного листа. Нужно выполнить команду меню `Стили ->
Управление стилями (F11)`, выбрать `Стили страниц` и двойным щелчком левой
кнопки мыши установить требуемый стиль.

При смене стиля форматной рамки с заполненной основной надписью -- данные
сохраняются.

Для второго и последующих листов всегда используется стиль *Последующие листы*.

Во всех перечисленных стилях страниц, в качестве форматной рамки выступает
фоновое изображение.


=== Основная надпись и графы форматной рамки

Графы основной надписи и форматной рамки построены из врезок. Заголовки граф
защищены от перемещения, изменения размера и редактирования. Графы,
предназначенные для ввода текста, защищены только от перемещения и изменения
размера. Не все графы форматной рамки имеют врезки для ввода текста. Например,
графа _Подп._ основной надписи врезок для ввода текста не имеет.

Все врезки основной надписи и форматной рамки принадлежат нижнему колонтитулу и
хранятся в стиле страницы. Каждый стиль первого листа имеет свой собственный
набор врезок. При внесении изменений в графу основной надписи или форматной
рамки, соответствующие врезки остальных стилей синхронизируются посредством
макросов. Это позволяет изменять вид первого листа без потери данных.

Структура стиля второго и последующих листов аналогична. Но здесь все графы
защищены от записи. Их значения синхронизируются с соответствующими врезками
первого листа с помощью макросов.

Номера и количество страниц подставляются автоматически средствами LibreOffice
(используются _поля_). Если в документе лишь одна страница, то графа _Листов_,
основной надписи первого листа, остаётся пустой. Это реализовано на основе
_скрытого абзаца_ с условием.

Автоматический подбор масштаба шрифта по ширине работает как при заполнении
основной надписи с помощью команды `Заполнить осн. надпись`, так и при вводе
текста вручную. Текст обрабатывается построчно.


=== Начертание текста

Содержимое документа и графы форматной рамки имеют собственные стили абзацев.
Но все они происходят от одного общего стиля -- _Базовый_ и наследуют его
свойства.

Чтобы изменить начертание текста во всём документе необходимо открыть окно
управления стилями, выполнив команду меню `Стили -> Управление стилями (F11)`,
и нажать кнопку `Стили абзацев`. В списке стилей нажать правой кнопкой мыши на
пункте _Базовый_ и в контекстном меню выбрать команду `Изменить...`. В
открывшемся диалоговом окне, на вкладке _Шрифт_, можно установить необходимое
начертание текста в поле _Стиль_. _Обычный_ стиль соответствует прямому
начертанию, а _Курсив_ -- наклонному. После применения изменений все надписи в
документе будут отображаться с указанным начертанием.


=== Размер шрифта

По умолчанию размер шрифта содержимого пояснительной записки равен 16 пунктам.
Это значение можно изменить так же как и начертание текста, путём
редактирования _базового_ стиля абзацев. При этом размер шрифта основной
надписи и граф форматной рамки останется без изменений, так как для этих
элементов документа заданы особые размеры шрифта и они используются вместо
родительского _базового_ стиля.
